export const morseToChar: { [key: string]: string } = {
  "·": "E",
  "−": "T",
  "··": "I",
  "·−": "A",
  "−·": "N",
  "−−": "M",
  "···": "S",
  "··−": "U",
  "·−·": "R",
  "·−−": "W",
  "−··": "D",
  "−·−": "K",
  "−−·": "G",
  "−−−": "O",
  "····": "H",
  "···−": "V",
  "··−·": "F",
  "··−−": "Ü",
  "·−··": "L",
  "·−·−": "Ä",
  "·−−·": "P",
  "·−−−": "J",
  "−···": "B",
  "−··−": "X",
  "−·−·": "C",
  "−·−−": "Y",
  "−−··": "Z",
  "−−·−": "Q",
  "−−−·": "Ö",
  "−−−−": "CH",
  "·····": "5",
  "····−": "4",
  "···−−": "3",
  "··−−−": "2",
  "·−−−−": "1",
  "−····": "6",
  "−−···": "7",
  "−−−··": "8",
  "−−−−·": "9",
  "−−−−−": "0",
};

export const decodeMorse = (sequence: string): string => {
  const result = morseToChar[sequence] || "?";
  console.log("[decodeMorse] invoked", { sequence, result });
  return result;
};
